// Generated by CoffeeScript 1.9.3
(function() {
  var MkView, fs, utils;

  fs = require('fs');

  utils = require('./utils');

  module.exports = MkView = (function() {
    function MkView(name, route) {
      var message;
      this.name = name;
      this.route = route;
      message = 'Please give your view a name and route: app gen [view_name] [route_name]';
      if (!(this.name && this.route)) {
        return console.log(message);
      }
      console.log('Generating view...');
      this.generateFiles();
      this.populateFiles();
      this.generateRoute();
      console.log("Generated view: [ " + this.name + " ]");
    }

    MkView.prototype.generateFiles = function() {
      fs.open(utils.paths.controller + (this.name + ".coffee"), 'w');
      fs.open(utils.paths.stylus + (this.name + ".styl"), 'w');
      return fs.open(utils.paths.jade + (this.name + ".jade"), 'w');
    };

    MkView.prototype.populateFiles = function() {
      fs.readFile(utils.paths.templates + 'controller.coffee', (function(_this) {
        return function(err, data) {
          return fs.writeFile(utils.paths.controller + (_this.name + ".coffee"), utils.generateTemplate(_this.name, data));
        };
      })(this));
      fs.writeFile(utils.paths.jade + (this.name + ".jade"), utils.jadeData(this.name));
      return fs.writeFile(utils.paths.stylus + (this.name + ".styl"), utils.stylusData(this.name));
    };

    MkView.prototype.generateRoute = function() {
      return fs.readFile(utils.paths.routes, (function(_this) {
        return function(err, data) {
          data = data.toString().replace(utils.route404(), '');
          fs.writeFile(utils.paths.routes, data);
          fs.appendFile(utils.paths.routes, utils.routeTemplate(_this.name, _this.route));
          return fs.appendFile(utils.paths.routes, utils.route404());
        };
      })(this));
    };

    return MkView;

  })();

}).call(this);
