// Generated by CoffeeScript 1.9.3
(function() {
  var ServiceGenerator, fs, utils;

  fs = require('fs');

  utils = require('./utils.js');

  ServiceGenerator = (function() {
    ServiceGenerator.prototype.paths = {
      templates: 'cli/templates/',
      services: 'src/coffee/services/'
    };

    function ServiceGenerator(name) {
      var message;
      message = 'Please give your service a name: ngapp gen [service_name]';
      if (!name) {
        return console.log(message);
      }
      console.log('Generating service...');
      this.name = name.toLowerCase();
      this.generateFile();
      this.populateFile();
      console.log("Generated service: [ " + this.name + " ]");
    }

    ServiceGenerator.prototype.generateFile = function() {
      return fs.open(this.paths.services + (this.name + ".coffee"), 'w');
    };

    ServiceGenerator.prototype.populateFile = function() {
      return fs.readFile(this.paths.templates + 'service.coffee', (function(_this) {
        return function(err, data) {
          return fs.writeFile(_this.paths.services + (_this.name + ".coffee"), utils.generateData(_this.name, data));
        };
      })(this));
    };

    return ServiceGenerator;

  })();

  module.exports = ServiceGenerator;

}).call(this);
