// Generated by CoffeeScript 1.9.3
(function() {
  var ServiceGenerator, fs, utils;

  fs = require('fs');

  utils = require('./utils.js');

  ServiceGenerator = (function() {
    function ServiceGenerator(type, name) {
      var message;
      message = 'Please give your service a type and name: ngapp gen-service [service_type] [service_name]';
      if (!(type && name)) {
        return console.log(message);
      }
      console.log('Generating service...');
      this.type = type.toLowerCase();
      this.name = name.toLowerCase();
      this.generateFile();
      this.populateFile();
      console.log("Generated service: [ " + this.name + " ]");
    }

    ServiceGenerator.prototype.generateFile = function() {
      return fs.open(utils.paths.services + (this.name + ".coffee"), 'w');
    };

    ServiceGenerator.prototype.populateFile = function() {
      return fs.readFile(utils.paths.templates + (this.type + ".coffee"), (function(_this) {
        return function(err, data) {
          return fs.writeFile(utils.paths.services + (_this.name + ".coffee"), utils.generateTemplate(_this.name, data));
        };
      })(this));
    };

    return ServiceGenerator;

  })();

  module.exports = ServiceGenerator;

}).call(this);
