// Generated by CoffeeScript 1.9.3
(function() {
  var Utils,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Utils = (function() {
    function Utils() {
      this.generateData = bind(this.generateData, this);
    }

    Utils.prototype.generateData = function(name, data) {
      return data.toString().replace(/<name>/g, this.capitalize(name));
    };

    Utils.prototype.capitalize = function(name) {
      return name.charAt(0).toUpperCase() + name.slice(1);
    };

    Utils.prototype.routeData = function(view, route) {
      var data;
      data = "\r\n \r\n			.when '/" + route + "', \r\n				templateUrl : 'templates/views/" + view + ".html' \r\n				controller  : '" + view + "Controller'";
      return data;
    };

    Utils.prototype.route404 = function() {
      var data;
      data = "\r\n \r\n			.otherwise \r\n				templateUrl : 'templates/views/404.html' \r\n				controller  : 'notFound404Controller'";
      return data;
    };

    Utils.prototype.jadeData = function(view) {
      var data;
      data = "#" + view + ".page \r\n \r\n	h1 " + (view.toUpperCase());
      return data;
    };

    Utils.prototype.stylusData = function(view) {
      var data;
      data = "#" + view + " \r\n	//";
      return data;
    };

    return Utils;

  })();

  module.exports = new Utils;

}).call(this);
