// Generated by CoffeeScript 1.9.3
(function() {
  var Utils,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Utils = (function() {
    function Utils() {
      this.generateTemplate = bind(this.generateTemplate, this);
    }

    Utils.prototype.paths = {
      templates: 'cli/templates/',
      controller: 'src/coffee/controllers/views/',
      service: 'src/coffee/services/',
      jade: 'src/jade/views/',
      stylus: 'src/stylus/views/',
      routes: 'src/coffee/routes/routes.coffee',
      html: 'public/templates/views/'
    };

    Utils.prototype.generateTemplate = function(name, data) {
      return data.toString().replace(/<name>/g, this.capitalize(name));
    };

    Utils.prototype.capitalize = function(name) {
      return name.charAt(0).toUpperCase() + name.slice(1);
    };

    Utils.prototype.routeTemplate = function(name, route) {
      var data;
      data = "\r\n \r\n			.when '/" + route + "', \r\n				templateUrl : 'templates/views/" + name + ".html' \r\n				controller  : '" + name + "Controller'";
      return data;
    };

    Utils.prototype.route404 = function() {
      var data;
      data = "\r\n \r\n			.otherwise \r\n				templateUrl : 'templates/views/404.html' \r\n				controller  : 'notFound404Controller'";
      return data;
    };

    Utils.prototype.jadeData = function(name) {
      var data;
      data = "#" + name + ".page \r\n \r\n	h1 " + (name.toUpperCase());
      return data;
    };

    Utils.prototype.stylusData = function(name) {
      var data;
      data = "#" + name + " \r\n	//";
      return data;
    };

    return Utils;

  })();

  module.exports = new Utils;

}).call(this);
