// Generated by CoffeeScript 1.9.3
(function() {
  var ViewDeleter, fs, utils;

  fs = require('fs');

  utils = require('./utils.js');

  ViewDeleter = (function() {
    function ViewDeleter(view, route) {
      var message;
      message = 'Please pass the name and route of the view you wish to delete: app del [view_name] [route_name]';
      if (!(view && route)) {
        return console.log(message);
      }
      console.log('Deleting view...');
      this.view = view.toLowerCase();
      this.route = route.toLowerCase();
      this.deleteFiles();
      this.deleteRoute();
      console.log("Deleted view: [ " + this.view + " ]");
    }

    ViewDeleter.prototype.deleteFiles = function() {
      fs.unlink(utils.paths.coffee + (this.view + ".coffee"), (function(_this) {
        return function(err) {
          if (err) {
            return _this.errorMessage(err);
          }
        };
      })(this));
      fs.unlink(utils.paths.jade + (this.view + ".jade"), (function(_this) {
        return function(err) {
          if (err) {
            return _this.errorMessage(err);
          }
        };
      })(this));
      fs.unlink(utils.paths.stylus + (this.view + ".styl"), (function(_this) {
        return function(err) {
          if (err) {
            return _this.errorMessage(err);
          }
        };
      })(this));
      return fs.unlink(utils.paths.html + (this.view + ".html"), (function(_this) {
        return function(err) {
          if (err) {
            return _this.errorMessage(err);
          }
        };
      })(this));
    };

    ViewDeleter.prototype.deleteRoute = function() {
      return fs.readFile(utils.paths.routes, (function(_this) {
        return function(err, data) {
          data = data.toString().replace(utils.routeTemplate(_this.view, _this.route), '');
          return fs.writeFile(utils.paths.routes, data);
        };
      })(this));
    };

    ViewDeleter.prototype.errorMessage = function(error) {
      return console.log("It looks like " + error.path + " wasn't found...");
    };

    return ViewDeleter;

  })();

  module.exports = ViewDeleter;

}).call(this);
