shjs = require 'shelljs/global'

commands = [
	"coffee -c cli/cli.coffee",
	"coffee -o cli/tasks -c cli/tasks/coffee/utils.coffee",
	"coffee -o cli/tasks -c cli/tasks/coffee/view_generator.coffee",
	"coffee -o cli/tasks -c cli/tasks/coffee/view_deleter.coffee",
	"coffee -o cli/tasks -c cli/tasks/coffee/service_generator.coffee"
]

taskRunner = ( command, index ) ->

	exec command, ( code ) ->

		if code is 0

			if index is 0
					
					# Replace generated coffeescript comment
					stupid = "// Generated by CoffeeScript 1.9.3"
					
					sed( '-i', stupid, '#!/usr/bin/env node', 'cli/cli.js' )
					
					echo 'Success: CLI build complete and shebang inserted!'

			else

				echo 'Success: build complete!'

		else

			echo 'Error: build failed...'
			exit 1

for command, index in commands

	taskRunner( command, index )