shjs = require 'shelljs/global'
fs   = require 'fs'

commands = [
	{ type: 'cli',     cmd: "coffee -c cli/cli.coffee" },
	{ type: 'utils',   cmd: "coffee -o cli/tasks -c cli/tasks/coffee/utils.coffee" },
	{ type: 'mk_view', cmd: "coffee -o cli/tasks -c cli/tasks/coffee/mk_view.coffee" },
	{ type: 'rm_view', cmd: "coffee -o cli/tasks -c cli/tasks/coffee/rm_view.coffee" }
]

taskRunner = ( command, index ) ->

	exec command.cmd, ( code ) ->

		if code is 0

			if index is 0
					
					# Replace generated coffeescript comment with node shebang
					stupid = "// Generated by CoffeeScript 1.9.3"
					
					sed( '-i', stupid, '#!/usr/bin/env node', 'cli/cli.js' )
					
					echo 'Success: CLI build complete and shebang inserted!'

			else

				echo "Success: #{command.type} build complete!"

		else

			echo "Error: #{command.type} build failed..."
			exit 1

for command, index in commands

	taskRunner( command, index )