shjs = require 'shelljs/global'

exec "coffee -c cli/cli.coffee", ( code, output ) ->

	# echo 'code', code
	# echo 'output', output

	if code is 0
	
		# Replace generated coffeescript comment
		stupid = "// Generated by CoffeeScript 1.9.3"
		
		sed( '-i', stupid, '#!/usr/bin/env node', 'cli/cli.js' )

		echo 'Cli build complete'

	else

		echo 'Error: cli build failed'

		exit 1